import mongoose from "mongoose";
import {
  ALL_ECO_TAX_MECHANISMS,
  ALL_GST_SUPPLY_TYPES,
  ALL_GST_TXN_TYPES,
  ALL_GST_SERVICE_TYPES,
  ALL_GST_TXN_STATUSES,
  ALL_E_INVOICE_STATUSES,
  ALL_SELLER_GST_STATUSES,
} from "../constants/finance.js";

/**
 * GstTransaction — Master GST ledger.
 *
 * Per delivered order, 3 types of records are created:
 *  1. SELLER_PRODUCT_SALE   — One record per line item (seller's outward supply)
 *  2. ZOOGNO_SERVICE_SALE   — Per service type: PLATFORM_FEE + DELIVERY_FEE (Zoogno's supply)
 *  3. ZOOGNO_SELLER_COMMISSION — One record per order (Zoogno's commission to seller)
 *
 * Credit/Debit notes are created for returns/refunds.
 *
 * All 5 CA-package CSVs are generated by querying this collection.
 */
const gstTransactionSchema = new mongoose.Schema(
  {
    // ── Identity ──────────────────────────────────────────────────────────────
    gstTxnId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      // e.g. ZTXN-2026-27-000001
    },

    // Transaction type determines which CSV this record contributes to
    txnType: {
      type: String,
      enum: ALL_GST_TXN_TYPES,
      required: true,
      index: true,
    },

    status: {
      type: String,
      enum: ALL_GST_TXN_STATUSES,
      default: "ACTIVE",
      index: true,
    },

    // ── Order Reference ───────────────────────────────────────────────────────
    orderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Order",
      required: true,
      index: true,
    },
    orderRefId: { type: String, index: true }, // human-readable orderId e.g. "ZOOGNO10001"

    // For SELLER_PRODUCT_SALE: index of the line item within the order
    lineItemIndex: { type: Number, default: 0 },
    lineItemId: { type: mongoose.Schema.Types.ObjectId }, // items[]._id

    // ── Reporting Period ──────────────────────────────────────────────────────
    financialYear: { type: String, index: true }, // e.g. "2026-27"
    taxPeriod: { type: String, index: true },     // e.g. "Aug-2026"
    taxPeriodDate: { type: Date, index: true },    // ISO date for range queries

    // ── Seller Information (for SELLER_PRODUCT_SALE & ZOOGNO_SELLER_COMMISSION) ─
    sellerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Seller",
      index: true,
    },
    sellerName: { type: String },
    sellerGstin: { type: String },             // null for unregistered
    sellerGstStatus: {
      type: String,
      enum: ALL_SELLER_GST_STATUSES,
      default: "UNREGISTERED",
    },
    sellerStateCode: { type: String },          // 2-digit state code
    sellerState: { type: String },              // Human-readable state name
    sellerEcoTaxMechanism: {
      type: String,
      enum: ALL_ECO_TAX_MECHANISMS,
      default: "SECTION_52_TCS",
    },

    // ── Customer Information ──────────────────────────────────────────────────
    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    customerName: { type: String },
    customerGstin: { type: String },            // null for B2C consumers
    customerType: {
      type: String,
      enum: ["B2B", "B2C"],
      default: "B2C",
    },
    customerState: { type: String },
    customerStateCode: { type: String },        // 2-digit state code

    // ── Supply Classification ─────────────────────────────────────────────────
    supplyType: {
      type: String,
      enum: ALL_GST_SUPPLY_TYPES,
      default: "B2C",
    },
    // Same state as Zoogno? → CGST+SGST; Different → IGST
    placeOfSupply: { type: String },            // State name
    placeOfSupplyCode: { type: String },        // 2-digit code
    isInterState: { type: Boolean, default: false },
    isUnionTerritory: { type: Boolean, default: false }, // UTGST instead of SGST

    // ECO mechanism applied for this specific transaction
    section: {
      type: String,
      enum: ALL_ECO_TAX_MECHANISMS,
      default: "SECTION_52_TCS",
    },

    // ── Invoice Details ───────────────────────────────────────────────────────
    // For SELLER_PRODUCT_SALE (Section 52): seller's own invoice details
    supplierInvoiceNo: { type: String },        // Seller's invoice number
    supplierInvoiceDate: { type: Date },

    // For ZOOGNO_SERVICE_SALE & ZOOGNO_SELLER_COMMISSION: Zoogno's invoice
    zoognoInvoiceNo: { type: String, index: true },
    zoognoInvoiceDate: { type: Date },
    zoognoInvoiceSeries: { type: String },      // ZG_INV / ZG_COM / ZG_CN / ZG_DN

    // ── Product / Service Line ────────────────────────────────────────────────
    productId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Product",
    },
    productName: { type: String },

    // HSN for products, SAC for services
    hsnSac: { type: String },
    quantity: { type: Number, default: 1 },
    unit: { type: String, default: "NOS" },

    // ── Tax Amounts (all in INR, 2 decimal places) ─────────────────────────────
    taxableValue: { type: Number, default: 0 },
    gstRate: { type: Number, default: 0 },      // Total GST rate %

    // Intra-state
    cgstRate: { type: Number, default: 0 },
    cgstAmount: { type: Number, default: 0 },
    sgstRate: { type: Number, default: 0 },
    sgstAmount: { type: Number, default: 0 },   // Also used for UTGST amount
    isUTGST: { type: Boolean, default: false },  // true = UTGST instead of SGST

    // Inter-state
    igstRate: { type: Number, default: 0 },
    igstAmount: { type: Number, default: 0 },

    // Cess
    cessRate: { type: Number, default: 0 },
    cessAmount: { type: Number, default: 0 },

    gstAmount: { type: Number, default: 0 },    // Total GST on this line
    invoiceTotal: { type: Number, default: 0 }, // taxableValue + gstAmount + cess

    // ── TCS (Section 52) ─────────────────────────────────────────────────────
    tcsApplicable: { type: Boolean, default: false },
    tcsRate: { type: Number, default: 0 },       // e.g. 1%
    tcsAmount: { type: Number, default: 0 },
    tcsGstin: { type: String },                  // Zoogno's TCS GSTIN (may differ from main)

    // ── Service-specific (for ZOOGNO_SERVICE_SALE) ────────────────────────────
    serviceType: {
      type: String,
      enum: ALL_GST_SERVICE_TYPES,
    },
    sacCode: { type: String },
    sacDescription: { type: String },

    // ── Commission-specific (for ZOOGNO_SELLER_COMMISSION) ───────────────────
    commissionPercentage: { type: Number, default: 0 },
    commissionBase: { type: Number, default: 0 },    // Gross order value commission was applied on
    commissionValue: { type: Number, default: 0 },   // Commission before GST
    commissionGstAmount: { type: Number, default: 0 },
    commissionInvoiceTotal: { type: Number, default: 0 },

    // ── Settlement ────────────────────────────────────────────────────────────
    settlementId: { type: String },     // Human-readable settlement ref
    payoutId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Payout",
    },
    settlementDate: { type: Date },
    settlementStatus: {
      type: String,
      enum: ["PENDING", "COMPLETED", "FAILED", "NOT_APPLICABLE"],
      default: "PENDING",
    },

    // ── Credit / Debit Notes ─────────────────────────────────────────────────
    isAdjustment: { type: Boolean, default: false },
    creditNoteNo: { type: String },
    debitNoteNo: { type: String },
    originalGstTxnId: { type: String }, // Links to the original ACTIVE txn
    originalInvoiceNo: { type: String },
    refundValue: { type: Number, default: 0 },
    adjustmentReason: { type: String },

    // ── E-Invoice (future-ready) ──────────────────────────────────────────────
    eInvoiceRequired: { type: Boolean, default: false },
    irn: { type: String },              // Invoice Reference Number from IRP
    irnDate: { type: Date },
    ackNo: { type: String },            // IRP Acknowledgement Number
    ackDate: { type: Date },
    eInvoiceStatus: {
      type: String,
      enum: ALL_E_INVOICE_STATUSES,
      default: "NOT_REQUIRED",
    },
    eInvoiceQrCode: { type: String },   // QR code string from IRP

    // ── Metadata ──────────────────────────────────────────────────────────────
    generatedAt: { type: Date, default: Date.now },
    generatedBy: { type: String, default: "SYSTEM" }, // SYSTEM | ADMIN | MIGRATION
    remarks: { type: String },
  },
  { timestamps: true },
);

// ── Indexes ───────────────────────────────────────────────────────────────────
gstTransactionSchema.index({ financialYear: 1, taxPeriod: 1 });
gstTransactionSchema.index({ financialYear: 1, taxPeriod: 1, txnType: 1 });
gstTransactionSchema.index({ sellerId: 1, financialYear: 1, taxPeriod: 1 });
gstTransactionSchema.index({ sellerGstin: 1, financialYear: 1 });
gstTransactionSchema.index({ sellerGstStatus: 1, txnType: 1 });
gstTransactionSchema.index({ section: 1, txnType: 1 });
gstTransactionSchema.index({ supplyType: 1, isInterState: 1 });
gstTransactionSchema.index({ orderId: 1, txnType: 1 });
gstTransactionSchema.index({ settlementId: 1 });
gstTransactionSchema.index({ taxPeriodDate: -1 });

export default mongoose.model("GstTransaction", gstTransactionSchema);
